import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/Components/Layout/Header";
import { OpenSansFont } from "@/Utils";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={OpenSansFont.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
